language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - python setup.py install
script:
  - reprozip testrun bash -c "cat /etc/passwd;echo"
  - reprozip trace bash -c "cat /etc/passwd;echo"
  - reprozip trace --continue sh -c "cat /etc/group;/usr/bin/id"
  - reprozip graph graph.dot
