language: python
env:
  - TEST_MODE=run_program
  - TEST_MODE=check_style
python:
  - "2.7"
  - "3.2"
  - "3.3"
install: .travis/install.sh
script: .travis/test.sh
notifications:
  email:
    recipients:
       - reprozip-dev@vgc.poly.edu
    on_success: change
    on_failure: always
matrix:
  exclude:
    - python: "3.2"
      env: TEST_MODE=check_style
